#ifndef PARAMETRIC_ERROR_H
#define PARAMETRIC_ERROR_H


#define	MEMORY_ALLOCATION_ERROR			-1
#define	INVALIDE_DATA_RANGE				-2
#define	DATA_RANGE_ERROR				-3
#define	LOGRITHM_OUTRANGE				-4
#define	NUMBER_INDEX_ERROR				-5
#define	INVALIDE_INPUT_ERROR			-6
#define DEBUG_TERMINATE					-7
#define	DATA_DISORDER_ERROR				-8
#define	ITERATION_OVERFLOW_ERROR		-9
#define	BISECTION_OVERFLOW_ERROR		-10
#define NUMERICAL_RECIPIENT_ERROR		-11
#define MATH_DOMAIN_ERROR				-12
#define MATH_SINGULARITY_ERROR			-13
#define MATH_OVERFLOW_ERROR				-14
#define MATH_UNDERFLOW_ERROR			-15
#define	MATH_TLOSS_ERROR				-16
#define MATH_UNEXPECTED_ERROR			-17
#define	INVALIDE_PRIOR_TYPE		 		-18
#define	INVALIDE_LIKELIHOOD				-19 //***
#define	NO_EVIDENCE						-20
#define	SAMPLING_ERROR					-30
#define INVALID_ARGUMENT				-101
#define NO_SOLUTION						-102
#define SMALL_ITMAX						-103

#endif