/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class redcas_numerical_NativeLogNormal */

#ifndef _Included_redcas_numerical_NativeLogNormal
#define _Included_redcas_numerical_NativeLogNormal
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     redcas_numerical_NativeLogNormal
 * Method:    getPDF
 * Signature: (DDD)D
 */
JNIEXPORT jdouble JNICALL Java_redcas_numerical_NativeLogNormal_getPDF
  (JNIEnv *, jclass, jdouble, jdouble, jdouble);

/*
 * Class:     redcas_numerical_NativeLogNormal
 * Method:    getCDF
 * Signature: (DDD)D
 */
JNIEXPORT jdouble JNICALL Java_redcas_numerical_NativeLogNormal_getCDF
  (JNIEnv *, jclass, jdouble, jdouble, jdouble);

/*
 * Class:     redcas_numerical_NativeLogNormal
 * Method:    getQuantile
 * Signature: (DDD)D
 */
JNIEXPORT jdouble JNICALL Java_redcas_numerical_NativeLogNormal_getQuantile
  (JNIEnv *, jclass, jdouble, jdouble, jdouble);

/*
 * Class:     redcas_numerical_NativeLogNormal
 * Method:    getMean
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_redcas_numerical_NativeLogNormal_getMean
  (JNIEnv *, jclass, jdouble, jdouble);

/*
 * Class:     redcas_numerical_NativeLogNormal
 * Method:    getVariance
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_redcas_numerical_NativeLogNormal_getVariance
  (JNIEnv *, jclass, jdouble, jdouble);

/*
 * Class:     redcas_numerical_NativeLogNormal
 * Method:    getMedian
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_redcas_numerical_NativeLogNormal_getMedian
  (JNIEnv *, jclass, jdouble, jdouble);

/*
 * Class:     redcas_numerical_NativeLogNormal
 * Method:    getSample
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_redcas_numerical_NativeLogNormal_getSample
  (JNIEnv *, jclass, jdouble, jdouble);

#ifdef __cplusplus
}
#endif
#endif
