/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class redcas_numerical_NativeDCDFLIB */

#ifndef _Included_redcas_numerical_NativeDCDFLIB
#define _Included_redcas_numerical_NativeDCDFLIB
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     redcas_numerical_NativeDCDFLIB
 * Method:    getGammaLn
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_redcas_numerical_NativeDCDFLIB_getGammaLn
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     redcas_numerical_NativeDCDFLIB
 * Method:    getDiGamma
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_redcas_numerical_NativeDCDFLIB_getDiGamma
  (JNIEnv *, jclass, jdouble);

#ifdef __cplusplus
}
#endif
#endif
