/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class redcas_license_LicenseController */

#ifndef _Included_redcas_license_LicenseController
#define _Included_redcas_license_LicenseController
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: systemid */
/* Inaccessible static: signature */
/* Inaccessible static: sigarr */
/* Inaccessible static: lastError */
/*
 * Class:     redcas_license_LicenseController
 * Method:    getSysIDN
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_redcas_license_LicenseController_getSysIDN
  (JNIEnv *, jclass);

/*
 * Class:     redcas_license_LicenseController
 * Method:    getStartTimeN
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_redcas_license_LicenseController_getStartTimeN
  (JNIEnv *, jclass);

/*
 * Class:     redcas_license_LicenseController
 * Method:    setStartTimeN
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_redcas_license_LicenseController_setStartTimeN
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
