/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class redcas_numerical_NativeNormal */

#ifndef _Included_redcas_numerical_NativeNormal
#define _Included_redcas_numerical_NativeNormal
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     redcas_numerical_NativeNormal
 * Method:    getPDF
 * Signature: (DDD)D
 */
JNIEXPORT jdouble JNICALL Java_redcas_numerical_NativeNormal_getPDF
  (JNIEnv *, jclass, jdouble, jdouble, jdouble);

/*
 * Class:     redcas_numerical_NativeNormal
 * Method:    getCDF
 * Signature: (DDD)D
 */
JNIEXPORT jdouble JNICALL Java_redcas_numerical_NativeNormal_getCDF
  (JNIEnv *, jclass, jdouble, jdouble, jdouble);

/*
 * Class:     redcas_numerical_NativeNormal
 * Method:    getQuantile
 * Signature: (DDD)D
 */
JNIEXPORT jdouble JNICALL Java_redcas_numerical_NativeNormal_getQuantile
  (JNIEnv *, jclass, jdouble, jdouble, jdouble);

/*
 * Class:     redcas_numerical_NativeNormal
 * Method:    getMean
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_redcas_numerical_NativeNormal_getMean
  (JNIEnv *, jclass, jdouble, jdouble);

/*
 * Class:     redcas_numerical_NativeNormal
 * Method:    getVariance
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_redcas_numerical_NativeNormal_getVariance
  (JNIEnv *, jclass, jdouble, jdouble);

/*
 * Class:     redcas_numerical_NativeNormal
 * Method:    getMedian
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_redcas_numerical_NativeNormal_getMedian
  (JNIEnv *, jclass, jdouble, jdouble);

/*
 * Class:     redcas_numerical_NativeNormal
 * Method:    getSample
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_redcas_numerical_NativeNormal_getSample
  (JNIEnv *, jclass, jdouble, jdouble);

#ifdef __cplusplus
}
#endif
#endif
