/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class redcas_util_imgexport_ImageToClipBoardCopier */

#ifndef _Included_redcas_util_imgexport_ImageToClipBoardCopier
#define _Included_redcas_util_imgexport_ImageToClipBoardCopier
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     redcas_util_imgexport_ImageToClipBoardCopier
 * Method:    copyToClipBoardN
 * Signature: (II[I)V
 */
JNIEXPORT void JNICALL Java_redcas_util_imgexport_ImageToClipBoardCopier_copyToClipBoardN
  (JNIEnv *, jclass, jint, jint, jintArray);

#ifdef __cplusplus
}
#endif
#endif
