/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class redcas_numerical_NativeGamma */

#ifndef _Included_redcas_numerical_NativeGamma
#define _Included_redcas_numerical_NativeGamma
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     redcas_numerical_NativeGamma
 * Method:    getPDF
 * Signature: (DDD)D
 */
JNIEXPORT jdouble JNICALL Java_redcas_numerical_NativeGamma_getPDF
  (JNIEnv *, jclass, jdouble, jdouble, jdouble);

/*
 * Class:     redcas_numerical_NativeGamma
 * Method:    getCDF
 * Signature: (DDD)D
 */
JNIEXPORT jdouble JNICALL Java_redcas_numerical_NativeGamma_getCDF
  (JNIEnv *, jclass, jdouble, jdouble, jdouble);

/*
 * Class:     redcas_numerical_NativeGamma
 * Method:    getQuantile
 * Signature: (DDD)D
 */
JNIEXPORT jdouble JNICALL Java_redcas_numerical_NativeGamma_getQuantile
  (JNIEnv *, jclass, jdouble, jdouble, jdouble);

/*
 * Class:     redcas_numerical_NativeGamma
 * Method:    getMean
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_redcas_numerical_NativeGamma_getMean
  (JNIEnv *, jclass, jdouble, jdouble);

/*
 * Class:     redcas_numerical_NativeGamma
 * Method:    getVariance
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_redcas_numerical_NativeGamma_getVariance
  (JNIEnv *, jclass, jdouble, jdouble);

/*
 * Class:     redcas_numerical_NativeGamma
 * Method:    getMedian
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_redcas_numerical_NativeGamma_getMedian
  (JNIEnv *, jclass, jdouble, jdouble);

/*
 * Class:     redcas_numerical_NativeGamma
 * Method:    getSample
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_redcas_numerical_NativeGamma_getSample
  (JNIEnv *, jclass, jdouble, jdouble);

/*
 * Class:     redcas_numerical_NativeGamma
 * Method:    solve
 * Signature: (DDDD[D)I
 */
JNIEXPORT jint JNICALL Java_redcas_numerical_NativeGamma_solve
  (JNIEnv *, jclass, jdouble, jdouble, jdouble, jdouble, jdoubleArray);

#ifdef __cplusplus
}
#endif
#endif
