/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class redcas_numerical_NativeNonHomog2 */

#ifndef _Included_redcas_numerical_NativeNonHomog2
#define _Included_redcas_numerical_NativeNonHomog2
#ifdef __cplusplus
extern "C" {
#endif
#undef redcas_numerical_NativeNonHomog2_DEFAULT_SAMPLE_SIZE
#define redcas_numerical_NativeNonHomog2_DEFAULT_SAMPLE_SIZE 5000L
#undef redcas_numerical_NativeNonHomog2_DPDMODE_LINEAR_INTERVAL
#define redcas_numerical_NativeNonHomog2_DPDMODE_LINEAR_INTERVAL 1L
#undef redcas_numerical_NativeNonHomog2_DPDMODE_LOGARITHMIC_INTERVAL
#define redcas_numerical_NativeNonHomog2_DPDMODE_LOGARITHMIC_INTERVAL 2L
#undef redcas_numerical_NativeNonHomog2_MARGINALMODE_LINEAR_INTERVAL
#define redcas_numerical_NativeNonHomog2_MARGINALMODE_LINEAR_INTERVAL 1L
#undef redcas_numerical_NativeNonHomog2_MARGINALMODE_LOGARITHMIC_INTERVAL
#define redcas_numerical_NativeNonHomog2_MARGINALMODE_LOGARITHMIC_INTERVAL 2L
#undef redcas_numerical_NativeNonHomog2_MARGINAL_ALPHA
#define redcas_numerical_NativeNonHomog2_MARGINAL_ALPHA 0L
#undef redcas_numerical_NativeNonHomog2_MARGINAL_BETA
#define redcas_numerical_NativeNonHomog2_MARGINAL_BETA 1L
#undef redcas_numerical_NativeNonHomog2_BETA_BINOMIAL
#define redcas_numerical_NativeNonHomog2_BETA_BINOMIAL 1L
#undef redcas_numerical_NativeNonHomog2_GAMMA_POISSON
#define redcas_numerical_NativeNonHomog2_GAMMA_POISSON 2L
#undef redcas_numerical_NativeNonHomog2_LOGNORM_LOGNORM
#define redcas_numerical_NativeNonHomog2_LOGNORM_LOGNORM 3L
#undef redcas_numerical_NativeNonHomog2_NORMAL_NORMAL
#define redcas_numerical_NativeNonHomog2_NORMAL_NORMAL 4L
#undef redcas_numerical_NativeNonHomog2_LOGNORM_POISSON
#define redcas_numerical_NativeNonHomog2_LOGNORM_POISSON 5L
#undef redcas_numerical_NativeNonHomog2_LOGNORM_BINOMIAL
#define redcas_numerical_NativeNonHomog2_LOGNORM_BINOMIAL 6L
#undef redcas_numerical_NativeNonHomog2_MEASURE_CDF
#define redcas_numerical_NativeNonHomog2_MEASURE_CDF 1L
#undef redcas_numerical_NativeNonHomog2_MEASURE_PDF
#define redcas_numerical_NativeNonHomog2_MEASURE_PDF 2L
#undef redcas_numerical_NativeNonHomog2_MEASURE_MEAN
#define redcas_numerical_NativeNonHomog2_MEASURE_MEAN 3L
#undef redcas_numerical_NativeNonHomog2_MEASURE_VARIANCE
#define redcas_numerical_NativeNonHomog2_MEASURE_VARIANCE 4L
#undef redcas_numerical_NativeNonHomog2_MEASURE_QUANTILE
#define redcas_numerical_NativeNonHomog2_MEASURE_QUANTILE 5L
#undef redcas_numerical_NativeNonHomog2_PARAMETER_DEFAULT
#define redcas_numerical_NativeNonHomog2_PARAMETER_DEFAULT 3L
#undef redcas_numerical_NativeNonHomog2_PRIOR_MEAN_STD_ERR
#define redcas_numerical_NativeNonHomog2_PRIOR_MEAN_STD_ERR 1L
#undef redcas_numerical_NativeNonHomog2_PRIOR_MEDIAN_EF
#define redcas_numerical_NativeNonHomog2_PRIOR_MEDIAN_EF 2L
#undef redcas_numerical_NativeNonHomog2_PRIOR_MEDIAN_SIGMA
#define redcas_numerical_NativeNonHomog2_PRIOR_MEDIAN_SIGMA 3L
/*
 * Class:     redcas_numerical_NativeNonHomog2
 * Method:    createSessionN
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_redcas_numerical_NativeNonHomog2_createSessionN
  (JNIEnv *, jclass);

/*
 * Class:     redcas_numerical_NativeNonHomog2
 * Method:    destroySessionN
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_redcas_numerical_NativeNonHomog2_destroySessionN
  (JNIEnv *, jclass, jint);

/*
 * Class:     redcas_numerical_NativeNonHomog2
 * Method:    clearDataN
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_redcas_numerical_NativeNonHomog2_clearDataN
  (JNIEnv *, jclass, jint);

/*
 * Class:     redcas_numerical_NativeNonHomog2
 * Method:    addDataPointN
 * Signature: (IDDDD)V
 */
JNIEXPORT void JNICALL Java_redcas_numerical_NativeNonHomog2_addDataPointN
  (JNIEnv *, jclass, jint, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     redcas_numerical_NativeNonHomog2
 * Method:    setModelN
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_redcas_numerical_NativeNonHomog2_setModelN
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     redcas_numerical_NativeNonHomog2
 * Method:    clearSamplesN
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_redcas_numerical_NativeNonHomog2_clearSamplesN
  (JNIEnv *, jclass, jint);

/*
 * Class:     redcas_numerical_NativeNonHomog2
 * Method:    addSampleN
 * Signature: (IDDD)V
 */
JNIEXPORT void JNICALL Java_redcas_numerical_NativeNonHomog2_addSampleN
  (JNIEnv *, jclass, jint, jdouble, jdouble, jdouble);

/*
 * Class:     redcas_numerical_NativeNonHomog2
 * Method:    getMeasureN
 * Signature: (IIDID)D
 */
JNIEXPORT jdouble JNICALL Java_redcas_numerical_NativeNonHomog2_getMeasureN
  (JNIEnv *, jclass, jint, jint, jdouble, jint, jdouble);

/*
 * Class:     redcas_numerical_NativeNonHomog2
 * Method:    getMeasureMeanN
 * Signature: (IIDI)D
 */
JNIEXPORT jdouble JNICALL Java_redcas_numerical_NativeNonHomog2_getMeasureMeanN
  (JNIEnv *, jclass, jint, jint, jdouble, jint);

/*
 * Class:     redcas_numerical_NativeNonHomog2
 * Method:    getUpperBoundN
 * Signature: (II)D
 */
JNIEXPORT jdouble JNICALL Java_redcas_numerical_NativeNonHomog2_getUpperBoundN
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     redcas_numerical_NativeNonHomog2
 * Method:    getLowerBoundN
 * Signature: (II)D
 */
JNIEXPORT jdouble JNICALL Java_redcas_numerical_NativeNonHomog2_getLowerBoundN
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     redcas_numerical_NativeNonHomog2
 * Method:    setSampleCountN
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_redcas_numerical_NativeNonHomog2_setSampleCountN
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     redcas_numerical_NativeNonHomog2
 * Method:    runAnalysisN
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_redcas_numerical_NativeNonHomog2_runAnalysisN
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     redcas_numerical_NativeNonHomog2
 * Method:    getSampleCountN
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_redcas_numerical_NativeNonHomog2_getSampleCountN
  (JNIEnv *, jclass, jint);

/*
 * Class:     redcas_numerical_NativeNonHomog2
 * Method:    getAlphaN
 * Signature: (II)D
 */
JNIEXPORT jdouble JNICALL Java_redcas_numerical_NativeNonHomog2_getAlphaN
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     redcas_numerical_NativeNonHomog2
 * Method:    getBetaN
 * Signature: (II)D
 */
JNIEXPORT jdouble JNICALL Java_redcas_numerical_NativeNonHomog2_getBetaN
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     redcas_numerical_NativeNonHomog2
 * Method:    getProbabilityN
 * Signature: (II)D
 */
JNIEXPORT jdouble JNICALL Java_redcas_numerical_NativeNonHomog2_getProbabilityN
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     redcas_numerical_NativeNonHomog2
 * Method:    constructBinsN
 * Signature: (IIZ)I
 */
JNIEXPORT jint JNICALL Java_redcas_numerical_NativeNonHomog2_constructBinsN
  (JNIEnv *, jclass, jint, jint, jboolean);

/*
 * Class:     redcas_numerical_NativeNonHomog2
 * Method:    constructBinsExN
 * Signature: (IIZDDDD)I
 */
JNIEXPORT jint JNICALL Java_redcas_numerical_NativeNonHomog2_constructBinsExN
  (JNIEnv *, jclass, jint, jint, jboolean, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     redcas_numerical_NativeNonHomog2
 * Method:    getBinSizeN
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_redcas_numerical_NativeNonHomog2_getBinSizeN
  (JNIEnv *, jclass, jint);

/*
 * Class:     redcas_numerical_NativeNonHomog2
 * Method:    getBinnedAlphaN
 * Signature: (II)D
 */
JNIEXPORT jdouble JNICALL Java_redcas_numerical_NativeNonHomog2_getBinnedAlphaN
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     redcas_numerical_NativeNonHomog2
 * Method:    getBinnedBetaN
 * Signature: (II)D
 */
JNIEXPORT jdouble JNICALL Java_redcas_numerical_NativeNonHomog2_getBinnedBetaN
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     redcas_numerical_NativeNonHomog2
 * Method:    getBinnedDensityN
 * Signature: (III)D
 */
JNIEXPORT jdouble JNICALL Java_redcas_numerical_NativeNonHomog2_getBinnedDensityN
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     redcas_numerical_NativeNonHomog2
 * Method:    constructMarginalN
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_redcas_numerical_NativeNonHomog2_constructMarginalN
  (JNIEnv *, jclass, jint, jint, jint, jint);

/*
 * Class:     redcas_numerical_NativeNonHomog2
 * Method:    getMarginalSizeN
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_redcas_numerical_NativeNonHomog2_getMarginalSizeN
  (JNIEnv *, jclass, jint);

/*
 * Class:     redcas_numerical_NativeNonHomog2
 * Method:    getMarginalProbabilityN
 * Signature: (II)D
 */
JNIEXPORT jdouble JNICALL Java_redcas_numerical_NativeNonHomog2_getMarginalProbabilityN
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     redcas_numerical_NativeNonHomog2
 * Method:    getMarginalValueN
 * Signature: (II)D
 */
JNIEXPORT jdouble JNICALL Java_redcas_numerical_NativeNonHomog2_getMarginalValueN
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     redcas_numerical_NativeNonHomog2
 * Method:    getStatusN
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_redcas_numerical_NativeNonHomog2_getStatusN
  (JNIEnv *, jclass, jint);

/*
 * Class:     redcas_numerical_NativeNonHomog2
 * Method:    getProgressN
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_redcas_numerical_NativeNonHomog2_getProgressN
  (JNIEnv *, jclass, jint);

/*
 * Class:     redcas_numerical_NativeNonHomog2
 * Method:    getStatusCodeN
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_redcas_numerical_NativeNonHomog2_getStatusCodeN
  (JNIEnv *, jclass, jint);

/*
 * Class:     redcas_numerical_NativeNonHomog2
 * Method:    requestCancelN
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_redcas_numerical_NativeNonHomog2_requestCancelN
  (JNIEnv *, jclass, jint);

/*
 * Class:     redcas_numerical_NativeNonHomog2
 * Method:    isCancelRequestedN
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_redcas_numerical_NativeNonHomog2_isCancelRequestedN
  (JNIEnv *, jclass, jint);

/*
 * Class:     redcas_numerical_NativeNonHomog2
 * Method:    clearStatusN
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_redcas_numerical_NativeNonHomog2_clearStatusN
  (JNIEnv *, jclass, jint);

/*
 * Class:     redcas_numerical_NativeNonHomog2
 * Method:    setLogNormalPriorN
 * Signature: (IIDDDD)V
 */
JNIEXPORT void JNICALL Java_redcas_numerical_NativeNonHomog2_setLogNormalPriorN
  (JNIEnv *, jclass, jint, jint, jdouble, jdouble, jdouble, jdouble);

#ifdef __cplusplus
}
#endif
#endif
