/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class redcas_numerical_NativeUEKT */

#ifndef _Included_redcas_numerical_NativeUEKT
#define _Included_redcas_numerical_NativeUEKT
#ifdef __cplusplus
extern "C" {
#endif
#undef redcas_numerical_NativeUEKT_PRIOR_GAMMA
#define redcas_numerical_NativeUEKT_PRIOR_GAMMA 1L
#undef redcas_numerical_NativeUEKT_PRIOR_LOGNORMAL
#define redcas_numerical_NativeUEKT_PRIOR_LOGNORMAL 2L
#undef redcas_numerical_NativeUEKT_PRIOR_BETA
#define redcas_numerical_NativeUEKT_PRIOR_BETA 3L
#undef redcas_numerical_NativeUEKT_INTERPRETATION_BINOMIAL
#define redcas_numerical_NativeUEKT_INTERPRETATION_BINOMIAL 2L
#undef redcas_numerical_NativeUEKT_INTERPRETATION_POISSON
#define redcas_numerical_NativeUEKT_INTERPRETATION_POISSON 3L
#undef redcas_numerical_NativeUEKT_RESULT_OK
#define redcas_numerical_NativeUEKT_RESULT_OK 0L
/*
 * Class:     redcas_numerical_NativeUEKT
 * Method:    nativeLogPoisson
 * Signature: (DD[I[D[D[D[D[DI)I
 */
JNIEXPORT jint JNICALL Java_redcas_numerical_NativeUEKT_nativeLogPoisson
  (JNIEnv *, jclass, jdouble, jdouble, jintArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jint);

/*
 * Class:     redcas_numerical_NativeUEKT
 * Method:    nativeGamPoisson
 * Signature: (DD[I[D[D[D[D[DI)I
 */
JNIEXPORT jint JNICALL Java_redcas_numerical_NativeUEKT_nativeGamPoisson
  (JNIEnv *, jclass, jdouble, jdouble, jintArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jint);

/*
 * Class:     redcas_numerical_NativeUEKT
 * Method:    nativeLogBinomial
 * Signature: (DD[I[D[D[D[D[DI)I
 */
JNIEXPORT jint JNICALL Java_redcas_numerical_NativeUEKT_nativeLogBinomial
  (JNIEnv *, jclass, jdouble, jdouble, jintArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jint);

/*
 * Class:     redcas_numerical_NativeUEKT
 * Method:    nativeBetBinomial
 * Signature: (DD[I[D[D[D[D[DI)I
 */
JNIEXPORT jint JNICALL Java_redcas_numerical_NativeUEKT_nativeBetBinomial
  (JNIEnv *, jclass, jdouble, jdouble, jintArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jint);

/*
 * Class:     redcas_numerical_NativeUEKT
 * Method:    nativeTabPoisson
 * Signature: ([D[DI[I[D[D[D[D[DI)I
 */
JNIEXPORT jint JNICALL Java_redcas_numerical_NativeUEKT_nativeTabPoisson
  (JNIEnv *, jclass, jdoubleArray, jdoubleArray, jint, jintArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jint);

/*
 * Class:     redcas_numerical_NativeUEKT
 * Method:    nativeTabBinomial
 * Signature: ([D[DI[I[D[D[D[D[DI)I
 */
JNIEXPORT jint JNICALL Java_redcas_numerical_NativeUEKT_nativeTabBinomial
  (JNIEnv *, jclass, jdoubleArray, jdoubleArray, jint, jintArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jint);

#ifdef __cplusplus
}
#endif
#endif
