/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class redcas_numerical_NativeDistributionMgr */

#ifndef _Included_redcas_numerical_NativeDistributionMgr
#define _Included_redcas_numerical_NativeDistributionMgr
#ifdef __cplusplus
extern "C" {
#endif
#undef redcas_numerical_NativeDistributionMgr_UNIFORM_BINOMIAL
#define redcas_numerical_NativeDistributionMgr_UNIFORM_BINOMIAL 200L
#undef redcas_numerical_NativeDistributionMgr_UNIFORM_POISSON
#define redcas_numerical_NativeDistributionMgr_UNIFORM_POISSON 201L
#undef redcas_numerical_NativeDistributionMgr_LOGUNIFORM_BINOMIAL
#define redcas_numerical_NativeDistributionMgr_LOGUNIFORM_BINOMIAL 202L
#undef redcas_numerical_NativeDistributionMgr_LOGUNIFORM_POISSON
#define redcas_numerical_NativeDistributionMgr_LOGUNIFORM_POISSON 203L
#undef redcas_numerical_NativeDistributionMgr_LOGNORMAL_BINOMIAL
#define redcas_numerical_NativeDistributionMgr_LOGNORMAL_BINOMIAL 204L
#undef redcas_numerical_NativeDistributionMgr_LOGNORMAL_POISSON
#define redcas_numerical_NativeDistributionMgr_LOGNORMAL_POISSON 205L
#undef redcas_numerical_NativeDistributionMgr_LOGTAB
#define redcas_numerical_NativeDistributionMgr_LOGTAB 206L
#undef redcas_numerical_NativeDistributionMgr_LINTAB
#define redcas_numerical_NativeDistributionMgr_LINTAB 207L
#undef redcas_numerical_NativeDistributionMgr_LINTAB_BINOMIAL
#define redcas_numerical_NativeDistributionMgr_LINTAB_BINOMIAL 208L
#undef redcas_numerical_NativeDistributionMgr_LOGTAB_BINOMIAL
#define redcas_numerical_NativeDistributionMgr_LOGTAB_BINOMIAL 209L
#undef redcas_numerical_NativeDistributionMgr_LINTAB_POISSON
#define redcas_numerical_NativeDistributionMgr_LINTAB_POISSON 210L
#undef redcas_numerical_NativeDistributionMgr_LOGTAB_POISSON
#define redcas_numerical_NativeDistributionMgr_LOGTAB_POISSON 211L
#undef redcas_numerical_NativeDistributionMgr_LINTAB_LOGNORMAL
#define redcas_numerical_NativeDistributionMgr_LINTAB_LOGNORMAL 212L
#undef redcas_numerical_NativeDistributionMgr_LOGTAB_LOGNORMAL
#define redcas_numerical_NativeDistributionMgr_LOGTAB_LOGNORMAL 213L
#undef redcas_numerical_NativeDistributionMgr_LINTAB_NORMAL
#define redcas_numerical_NativeDistributionMgr_LINTAB_NORMAL 214L
#undef redcas_numerical_NativeDistributionMgr_LOGTAB_NORMAL
#define redcas_numerical_NativeDistributionMgr_LOGTAB_NORMAL 215L
#undef redcas_numerical_NativeDistributionMgr_LINTAB_LOGNORMAL_POISSON
#define redcas_numerical_NativeDistributionMgr_LINTAB_LOGNORMAL_POISSON 216L
#undef redcas_numerical_NativeDistributionMgr_LOGTAB_LOGNORMAL_POISSON
#define redcas_numerical_NativeDistributionMgr_LOGTAB_LOGNORMAL_POISSON 217L
#undef redcas_numerical_NativeDistributionMgr_LINTAB_LOGNORMAL_BINOMIAL
#define redcas_numerical_NativeDistributionMgr_LINTAB_LOGNORMAL_BINOMIAL 218L
#undef redcas_numerical_NativeDistributionMgr_LOGTAB_LOGNORMAL_BINOMIAL
#define redcas_numerical_NativeDistributionMgr_LOGTAB_LOGNORMAL_BINOMIAL 219L
/*
 * Class:     redcas_numerical_NativeDistributionMgr
 * Method:    create
 * Signature: (IDDDD)I
 */
JNIEXPORT jint JNICALL Java_redcas_numerical_NativeDistributionMgr_create
  (JNIEnv *, jclass, jint, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     redcas_numerical_NativeDistributionMgr
 * Method:    createTabular
 * Signature: (I[D[DDD)I
 */
JNIEXPORT jint JNICALL Java_redcas_numerical_NativeDistributionMgr_createTabular
  (JNIEnv *, jclass, jint, jdoubleArray, jdoubleArray, jdouble, jdouble);

/*
 * Class:     redcas_numerical_NativeDistributionMgr
 * Method:    createTabular4
 * Signature: (I[D[DDDDD)I
 */
JNIEXPORT jint JNICALL Java_redcas_numerical_NativeDistributionMgr_createTabular4
  (JNIEnv *, jclass, jint, jdoubleArray, jdoubleArray, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     redcas_numerical_NativeDistributionMgr
 * Method:    destroy
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_redcas_numerical_NativeDistributionMgr_destroy
  (JNIEnv *, jclass, jint);

/*
 * Class:     redcas_numerical_NativeDistributionMgr
 * Method:    getPDF
 * Signature: (ID)D
 */
JNIEXPORT jdouble JNICALL Java_redcas_numerical_NativeDistributionMgr_getPDF
  (JNIEnv *, jclass, jint, jdouble);

/*
 * Class:     redcas_numerical_NativeDistributionMgr
 * Method:    getCDF
 * Signature: (ID)D
 */
JNIEXPORT jdouble JNICALL Java_redcas_numerical_NativeDistributionMgr_getCDF
  (JNIEnv *, jclass, jint, jdouble);

/*
 * Class:     redcas_numerical_NativeDistributionMgr
 * Method:    getTabularCDF
 * Signature: (II)D
 */
JNIEXPORT jdouble JNICALL Java_redcas_numerical_NativeDistributionMgr_getTabularCDF
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     redcas_numerical_NativeDistributionMgr
 * Method:    getQuantile
 * Signature: (ID)D
 */
JNIEXPORT jdouble JNICALL Java_redcas_numerical_NativeDistributionMgr_getQuantile
  (JNIEnv *, jclass, jint, jdouble);

/*
 * Class:     redcas_numerical_NativeDistributionMgr
 * Method:    getMean
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_redcas_numerical_NativeDistributionMgr_getMean
  (JNIEnv *, jclass, jint);

/*
 * Class:     redcas_numerical_NativeDistributionMgr
 * Method:    getMedian
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_redcas_numerical_NativeDistributionMgr_getMedian
  (JNIEnv *, jclass, jint);

/*
 * Class:     redcas_numerical_NativeDistributionMgr
 * Method:    getVariance
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_redcas_numerical_NativeDistributionMgr_getVariance
  (JNIEnv *, jclass, jint);

/*
 * Class:     redcas_numerical_NativeDistributionMgr
 * Method:    getSample
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_redcas_numerical_NativeDistributionMgr_getSample
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
