/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class redcas_numerical_NativeTrLogNormal */

#ifndef _Included_redcas_numerical_NativeTrLogNormal
#define _Included_redcas_numerical_NativeTrLogNormal
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     redcas_numerical_NativeTrLogNormal
 * Method:    getPDF
 * Signature: (DDD)D
 */
JNIEXPORT jdouble JNICALL Java_redcas_numerical_NativeTrLogNormal_getPDF
  (JNIEnv *, jclass, jdouble, jdouble, jdouble);

/*
 * Class:     redcas_numerical_NativeTrLogNormal
 * Method:    getCDF
 * Signature: (DDD)D
 */
JNIEXPORT jdouble JNICALL Java_redcas_numerical_NativeTrLogNormal_getCDF
  (JNIEnv *, jclass, jdouble, jdouble, jdouble);

/*
 * Class:     redcas_numerical_NativeTrLogNormal
 * Method:    getQuantile
 * Signature: (DDD)D
 */
JNIEXPORT jdouble JNICALL Java_redcas_numerical_NativeTrLogNormal_getQuantile
  (JNIEnv *, jclass, jdouble, jdouble, jdouble);

/*
 * Class:     redcas_numerical_NativeTrLogNormal
 * Method:    getMean
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_redcas_numerical_NativeTrLogNormal_getMean
  (JNIEnv *, jclass, jdouble, jdouble);

/*
 * Class:     redcas_numerical_NativeTrLogNormal
 * Method:    getVariance
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_redcas_numerical_NativeTrLogNormal_getVariance
  (JNIEnv *, jclass, jdouble, jdouble);

/*
 * Class:     redcas_numerical_NativeTrLogNormal
 * Method:    getMedian
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_redcas_numerical_NativeTrLogNormal_getMedian
  (JNIEnv *, jclass, jdouble, jdouble);

/*
 * Class:     redcas_numerical_NativeTrLogNormal
 * Method:    getSample
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_redcas_numerical_NativeTrLogNormal_getSample
  (JNIEnv *, jclass, jdouble, jdouble);

#ifdef __cplusplus
}
#endif
#endif
