#ifndef __WEIBULL_DEFS_H
#define __WEIBULL_DEFS_H

#undef redcas_ErrorCode_InvalidHandle 
#define redcas_ErrorCode_InvalidHandle -1

#undef REDCASSRV_MEANSD_MODE
#define REDCASSRV_MEANSD_MODE 501L

#undef REDCASSRV_5TH95TH_MODE
#define REDCASSRV_5TH95TH_MODE 502L

#undef REDCASSRV_ALPHATHETA_MODE
#define REDCASSRV_ALPHATHETA_MODE 503L

#undef REDCASSRV_MEDIANTAU_MODE
#define REDCASSRV_MEDIANTAU_MODE 504L

#undef REDCASSRV_MEDIANEF_MODE
#define REDCASSRV_MEDIANEF_MODE 505L

#undef REDCASSRV_MEANEF_MODE
#define REDCASSRV_MEANEF_MODE 506L

#undef REDCASSRV_NUTAU_MODE
#define REDCASSRV_NUTAU_MODE 507L

#undef REDCASSRV_MINMAX_MODE
#define REDCASSRV_MINMAX_MODE 508L

#undef REDCASSRV_EVENTTIME_MODE
#define REDCASSRV_EVENTTIME_MODE 509L

#undef REDCASSRV_EVENTDEMANDS_MODE
#define REDCASSRV_EVENTDEMANDS_MODE 510L

#undef REDCASSRV_DEGREEOFFREEDOM
#define REDCASSRV_DEGREEOFFREEDOM 511L

#undef REDCASSRV_LAMBDA
#define REDCASSRV_LABMDA 512L

#undef REDCASSRV_SHAPESCALE
#define REDCASSRV_SHAPESCALE 513L

#undef brass_algorithmic_BRASSEngineNative_MEASURE_CUMULATIVE
#define brass_algorithmic_BRASSEngineNative_MEASURE_CUMULATIVE 12L

#undef brass_algorithmic_BRASSEngineNative_MEASURE_INTENSITY
#define brass_algorithmic_BRASSEngineNative_MEASURE_INTENSITY 13L

#undef brass_algorithmic_BRASSEngineNative_MEASURE_RELIABILITY
#define brass_algorithmic_BRASSEngineNative_MEASURE_RELIABILITY 11L

#undef brass_algorithmic_BRASSEngineNative_MEASURE_UNRELIABILITY
#define brass_algorithmic_BRASSEngineNative_MEASURE_UNRELIABILITY 20L


#endif