// RDATSrvObj.idl : IDL source for RDATSrvObj.dll
//

// This file will be processed by the MIDL tool to
// produce the type library (RDATSrvObj.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";
	[
		object,
		uuid(CF739BAA-54E6-40E1-8022-14AEB5D73482),
		dual,
		helpstring("IRedcassrv Interface"),
		pointer_default(unique)
	]
	interface IRedcassrv : IDispatch
	{
		[id(1), helpstring("method destroy")] HRESULT destroy([in] int iHandle);
		[id(3), helpstring("method create")] HRESULT create([in] int type, [in] double p1, [in] double p2, [in] double p3, [in] double p4, [out, retval] int * piHandle);
		[id(4), helpstring("method getPDF")] HRESULT getPDF([in] int iHandle, [in] double x, [out, retval] double * pdPDF);
		[id(5), helpstring("method getCDF")] HRESULT getCDF([in] int iHandle, [in] double x, [out, retval] double * pdCDF);
		[id(6), helpstring("method getQuantile")] HRESULT getQuantile([in] int iHandle, [in] double z, [out, retval] double * pdQuantile);
		[id(7), helpstring("method getMean")] HRESULT getMean([in] int iHandle, [out, retval] double * pdMean);
		[id(8), helpstring("method getMedian")] HRESULT getMedian([in] int iHandle, [out, retval] double * pdMedian);
		[id(9), helpstring("method getVariance")] HRESULT getVariance([in] int iHandle, [out, retval] double * pdVariance);
		[id(10), helpstring("method creates")] HRESULT creates([in] int type, [in] double p1, [in] double p2, [out, retval] int * piHandle);
	};

[
	uuid(0655D9D3-80B1-4E0A-B77E-57A8CAC395DF),
	version(1.0),
	helpstring("RDATSrvObj 1.0 Type Library")
]
library RDATSRVOBJLib
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");

	[
		uuid(511B4161-7EE5-4619-995D-F3FB5DC8256F),
		helpstring("_IRedcassrvEvents Interface")
	]
	dispinterface _IRedcassrvEvents
	{
		properties:
		methods:
	};

	[
		uuid(9B87ED66-DE7A-4B33-BEDB-479A58DD79AD),
		helpstring("Redcassrv Class")
	]
	coclass Redcassrv
	{
		[default] interface IRedcassrv;
		[default, source] dispinterface _IRedcassrvEvents;
	};
};
