/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class fiat_rdatsrv_homogeneous_NativeHomogeneous */

#ifndef _Included_fiat_rdatsrv_homogeneous_NativeHomogeneous
#define _Included_fiat_rdatsrv_homogeneous_NativeHomogeneous
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     fiat_rdatsrv_homogeneous_NativeHomogeneous
 * Method:    create
 * Signature: (IIDDIIDD)I
 */
JNIEXPORT jint JNICALL Java_fiat_rdatsrv_homogeneous_NativeHomogeneous_create
  (JNIEnv *, jobject, jint, jint, jdouble, jdouble, jint, jint, jdouble, jdouble);

/*
 * Class:     fiat_rdatsrv_homogeneous_NativeHomogeneous
 * Method:    destroy
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_fiat_rdatsrv_homogeneous_NativeHomogeneous_destroy
  (JNIEnv *, jobject, jint);

/*
 * Class:     fiat_rdatsrv_homogeneous_NativeHomogeneous
 * Method:    getPDF
 * Signature: (ID)D
 */
JNIEXPORT jdouble JNICALL Java_fiat_rdatsrv_homogeneous_NativeHomogeneous_getPDF
  (JNIEnv *, jobject, jint, jdouble);

/*
 * Class:     fiat_rdatsrv_homogeneous_NativeHomogeneous
 * Method:    getCDF
 * Signature: (ID)D
 */
JNIEXPORT jdouble JNICALL Java_fiat_rdatsrv_homogeneous_NativeHomogeneous_getCDF
  (JNIEnv *, jobject, jint, jdouble);

/*
 * Class:     fiat_rdatsrv_homogeneous_NativeHomogeneous
 * Method:    getQuantile
 * Signature: (ID)D
 */
JNIEXPORT jdouble JNICALL Java_fiat_rdatsrv_homogeneous_NativeHomogeneous_getQuantile
  (JNIEnv *, jobject, jint, jdouble);

/*
 * Class:     fiat_rdatsrv_homogeneous_NativeHomogeneous
 * Method:    getMean
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_fiat_rdatsrv_homogeneous_NativeHomogeneous_getMean
  (JNIEnv *, jobject, jint);

/*
 * Class:     fiat_rdatsrv_homogeneous_NativeHomogeneous
 * Method:    getMedian
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_fiat_rdatsrv_homogeneous_NativeHomogeneous_getMedian
  (JNIEnv *, jobject, jint);

/*
 * Class:     fiat_rdatsrv_homogeneous_NativeHomogeneous
 * Method:    getVariance
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_fiat_rdatsrv_homogeneous_NativeHomogeneous_getVariance
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
