/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class fiat_rdatsrv_nonhomogeneous_NativeNonHomogeneous */

#ifndef _Included_fiat_rdatsrv_nonhomogeneous_NativeNonHomogeneous
#define _Included_fiat_rdatsrv_nonhomogeneous_NativeNonHomogeneous
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     fiat_rdatsrv_nonhomogeneous_NativeNonHomogeneous
 * Method:    createSessionN
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_fiat_rdatsrv_nonhomogeneous_NativeNonHomogeneous_createSessionN
  (JNIEnv *, jobject);

/*
 * Class:     fiat_rdatsrv_nonhomogeneous_NativeNonHomogeneous
 * Method:    destroySessionN
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_fiat_rdatsrv_nonhomogeneous_NativeNonHomogeneous_destroySessionN
  (JNIEnv *, jobject, jint);

/*
 * Class:     fiat_rdatsrv_nonhomogeneous_NativeNonHomogeneous
 * Method:    setModelN
 * Signature: (IIDDDD)V
 */
JNIEXPORT void JNICALL Java_fiat_rdatsrv_nonhomogeneous_NativeNonHomogeneous_setModelN
  (JNIEnv *, jobject, jint, jint, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     fiat_rdatsrv_nonhomogeneous_NativeNonHomogeneous
 * Method:    runAnalysisN
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_fiat_rdatsrv_nonhomogeneous_NativeNonHomogeneous_runAnalysisN
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     fiat_rdatsrv_nonhomogeneous_NativeNonHomogeneous
 * Method:    addDataPoint
 * Signature: (IDDDD)V
 */
JNIEXPORT void JNICALL Java_fiat_rdatsrv_nonhomogeneous_NativeNonHomogeneous_addDataPoint
  (JNIEnv *, jobject, jint, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     fiat_rdatsrv_nonhomogeneous_NativeNonHomogeneous
 * Method:    getProgress
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_fiat_rdatsrv_nonhomogeneous_NativeNonHomogeneous_getProgress
  (JNIEnv *, jobject, jint);

/*
 * Class:     fiat_rdatsrv_nonhomogeneous_NativeNonHomogeneous
 * Method:    getSampleCount
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_fiat_rdatsrv_nonhomogeneous_NativeNonHomogeneous_getSampleCount
  (JNIEnv *, jobject, jint);

/*
 * Class:     fiat_rdatsrv_nonhomogeneous_NativeNonHomogeneous
 * Method:    constructBins
 * Signature: (IIZ)Z
 */
JNIEXPORT jboolean JNICALL Java_fiat_rdatsrv_nonhomogeneous_NativeNonHomogeneous_constructBins
  (JNIEnv *, jobject, jint, jint, jboolean);

/*
 * Class:     fiat_rdatsrv_nonhomogeneous_NativeNonHomogeneous
 * Method:    getBinnedAlpha
 * Signature: (II)D
 */
JNIEXPORT jdouble JNICALL Java_fiat_rdatsrv_nonhomogeneous_NativeNonHomogeneous_getBinnedAlpha
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     fiat_rdatsrv_nonhomogeneous_NativeNonHomogeneous
 * Method:    getBinnedBeta
 * Signature: (II)D
 */
JNIEXPORT jdouble JNICALL Java_fiat_rdatsrv_nonhomogeneous_NativeNonHomogeneous_getBinnedBeta
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     fiat_rdatsrv_nonhomogeneous_NativeNonHomogeneous
 * Method:    getBinnedDensity
 * Signature: (III)D
 */
JNIEXPORT jdouble JNICALL Java_fiat_rdatsrv_nonhomogeneous_NativeNonHomogeneous_getBinnedDensity
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     fiat_rdatsrv_nonhomogeneous_NativeNonHomogeneous
 * Method:    getPopVarMeanMean
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_fiat_rdatsrv_nonhomogeneous_NativeNonHomogeneous_getPopVarMeanMean
  (JNIEnv *, jobject, jint);

/*
 * Class:     fiat_rdatsrv_nonhomogeneous_NativeNonHomogeneous
 * Method:    getPopVarVarianceMean
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_fiat_rdatsrv_nonhomogeneous_NativeNonHomogeneous_getPopVarVarianceMean
  (JNIEnv *, jobject, jint);

/*
 * Class:     fiat_rdatsrv_nonhomogeneous_NativeNonHomogeneous
 * Method:    getPopVarMeanPercentile
 * Signature: (ID)D
 */
JNIEXPORT jdouble JNICALL Java_fiat_rdatsrv_nonhomogeneous_NativeNonHomogeneous_getPopVarMeanPercentile
  (JNIEnv *, jobject, jint, jdouble);

/*
 * Class:     fiat_rdatsrv_nonhomogeneous_NativeNonHomogeneous
 * Method:    getPopVarPercentilePercentile
 * Signature: (IDD)D
 */
JNIEXPORT jdouble JNICALL Java_fiat_rdatsrv_nonhomogeneous_NativeNonHomogeneous_getPopVarPercentilePercentile
  (JNIEnv *, jobject, jint, jdouble, jdouble);

/*
 * Class:     fiat_rdatsrv_nonhomogeneous_NativeNonHomogeneous
 * Method:    getMarginalSize
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_fiat_rdatsrv_nonhomogeneous_NativeNonHomogeneous_getMarginalSize
  (JNIEnv *, jobject, jint);

/*
 * Class:     fiat_rdatsrv_nonhomogeneous_NativeNonHomogeneous
 * Method:    getMarginalAlpha
 * Signature: (IIZ)I
 */
JNIEXPORT jint JNICALL Java_fiat_rdatsrv_nonhomogeneous_NativeNonHomogeneous_getMarginalAlpha
  (JNIEnv *, jobject, jint, jint, jboolean);

/*
 * Class:     fiat_rdatsrv_nonhomogeneous_NativeNonHomogeneous
 * Method:    getMarginalBeta
 * Signature: (IIZ)I
 */
JNIEXPORT jint JNICALL Java_fiat_rdatsrv_nonhomogeneous_NativeNonHomogeneous_getMarginalBeta
  (JNIEnv *, jobject, jint, jint, jboolean);

/*
 * Class:     fiat_rdatsrv_nonhomogeneous_NativeNonHomogeneous
 * Method:    getStatusCode
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_fiat_rdatsrv_nonhomogeneous_NativeNonHomogeneous_getStatusCode
  (JNIEnv *, jobject, jint);

/*
 * Class:     fiat_rdatsrv_nonhomogeneous_NativeNonHomogeneous
 * Method:    requestCancel
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_fiat_rdatsrv_nonhomogeneous_NativeNonHomogeneous_requestCancel
  (JNIEnv *, jobject, jint);

/*
 * Class:     fiat_rdatsrv_nonhomogeneous_NativeNonHomogeneous
 * Method:    getUpperBound
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_fiat_rdatsrv_nonhomogeneous_NativeNonHomogeneous_getUpperBound
  (JNIEnv *, jobject, jint);

/*
 * Class:     fiat_rdatsrv_nonhomogeneous_NativeNonHomogeneous
 * Method:    getLowerBound
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_fiat_rdatsrv_nonhomogeneous_NativeNonHomogeneous_getLowerBound
  (JNIEnv *, jobject, jint);

/*
 * Class:     fiat_rdatsrv_nonhomogeneous_NativeNonHomogeneous
 * Method:    clearData
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_fiat_rdatsrv_nonhomogeneous_NativeNonHomogeneous_clearData
  (JNIEnv *, jobject, jint);

/*
 * Class:     fiat_rdatsrv_nonhomogeneous_NativeNonHomogeneous
 * Method:    clearSamplesN
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_fiat_rdatsrv_nonhomogeneous_NativeNonHomogeneous_clearSamplesN
  (JNIEnv *, jobject, jint);

/*
 * Class:     fiat_rdatsrv_nonhomogeneous_NativeNonHomogeneous
 * Method:    getPopVarCDF
 * Signature: (IDD)D
 */
JNIEXPORT jdouble JNICALL Java_fiat_rdatsrv_nonhomogeneous_NativeNonHomogeneous_getPopVarCDF
  (JNIEnv *, jobject, jint, jdouble, jdouble);

/*
 * Class:     fiat_rdatsrv_nonhomogeneous_NativeNonHomogeneous
 * Method:    getPopVarPDF
 * Signature: (IDD)D
 */
JNIEXPORT jdouble JNICALL Java_fiat_rdatsrv_nonhomogeneous_NativeNonHomogeneous_getPopVarPDF
  (JNIEnv *, jobject, jint, jdouble, jdouble);

/*
 * Class:     fiat_rdatsrv_nonhomogeneous_NativeNonHomogeneous
 * Method:    getPopVarCDFMean
 * Signature: (ID)D
 */
JNIEXPORT jdouble JNICALL Java_fiat_rdatsrv_nonhomogeneous_NativeNonHomogeneous_getPopVarCDFMean
  (JNIEnv *, jobject, jint, jdouble);

/*
 * Class:     fiat_rdatsrv_nonhomogeneous_NativeNonHomogeneous
 * Method:    getPopVarPDFMean
 * Signature: (ID)D
 */
JNIEXPORT jdouble JNICALL Java_fiat_rdatsrv_nonhomogeneous_NativeNonHomogeneous_getPopVarPDFMean
  (JNIEnv *, jobject, jint, jdouble);

#ifdef __cplusplus
}
#endif
#endif
