/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class fiat_rdatsrv_weibull_NativeWeibull */

#ifndef _Included_fiat_rdatsrv_weibull_NativeWeibull
#define _Included_fiat_rdatsrv_weibull_NativeWeibull
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     fiat_rdatsrv_weibull_NativeWeibull
 * Method:    createWeibullSession
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_fiat_rdatsrv_weibull_NativeWeibull_createWeibullSession
  (JNIEnv *, jobject);

/*
 * Class:     fiat_rdatsrv_weibull_NativeWeibull
 * Method:    destroyWeibullSession
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_fiat_rdatsrv_weibull_NativeWeibull_destroyWeibullSession
  (JNIEnv *, jobject, jint);

/*
 * Class:     fiat_rdatsrv_weibull_NativeWeibull
 * Method:    initialize
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_fiat_rdatsrv_weibull_NativeWeibull_initialize
  (JNIEnv *, jobject, jint);

/*
 * Class:     fiat_rdatsrv_weibull_NativeWeibull
 * Method:    createTestDataSet
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_fiat_rdatsrv_weibull_NativeWeibull_createTestDataSet
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     fiat_rdatsrv_weibull_NativeWeibull
 * Method:    setTestDataRecord
 * Signature: (IIDDZ)I
 */
JNIEXPORT jint JNICALL Java_fiat_rdatsrv_weibull_NativeWeibull_setTestDataRecord
  (JNIEnv *, jobject, jint, jint, jdouble, jdouble, jboolean);

/*
 * Class:     fiat_rdatsrv_weibull_NativeWeibull
 * Method:    attachTestDataSet
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_fiat_rdatsrv_weibull_NativeWeibull_attachTestDataSet
  (JNIEnv *, jobject, jint);

/*
 * Class:     fiat_rdatsrv_weibull_NativeWeibull
 * Method:    createGroupedDataSet
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_fiat_rdatsrv_weibull_NativeWeibull_createGroupedDataSet
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     fiat_rdatsrv_weibull_NativeWeibull
 * Method:    setGroupedDataRecord
 * Signature: (IIDDII)I
 */
JNIEXPORT jint JNICALL Java_fiat_rdatsrv_weibull_NativeWeibull_setGroupedDataRecord
  (JNIEnv *, jobject, jint, jint, jdouble, jdouble, jint, jint);

/*
 * Class:     fiat_rdatsrv_weibull_NativeWeibull
 * Method:    attachGroupedDataSet
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_fiat_rdatsrv_weibull_NativeWeibull_attachGroupedDataSet
  (JNIEnv *, jobject, jint);

/*
 * Class:     fiat_rdatsrv_weibull_NativeWeibull
 * Method:    setShapePrior
 * Signature: (IIDD)I
 */
JNIEXPORT jint JNICALL Java_fiat_rdatsrv_weibull_NativeWeibull_setShapePrior
  (JNIEnv *, jobject, jint, jint, jdouble, jdouble);

/*
 * Class:     fiat_rdatsrv_weibull_NativeWeibull
 * Method:    setLogNormalScalePrior
 * Signature: (IIDD)I
 */
JNIEXPORT jint JNICALL Java_fiat_rdatsrv_weibull_NativeWeibull_setLogNormalScalePrior
  (JNIEnv *, jobject, jint, jint, jdouble, jdouble);

/*
 * Class:     fiat_rdatsrv_weibull_NativeWeibull
 * Method:    setRxCxScalePrior
 * Signature: (IDDD)I
 */
JNIEXPORT jint JNICALL Java_fiat_rdatsrv_weibull_NativeWeibull_setRxCxScalePrior
  (JNIEnv *, jobject, jint, jdouble, jdouble, jdouble);

/*
 * Class:     fiat_rdatsrv_weibull_NativeWeibull
 * Method:    setI1000ScalePrior
 * Signature: (IDDD)I
 */
JNIEXPORT jint JNICALL Java_fiat_rdatsrv_weibull_NativeWeibull_setI1000ScalePrior
  (JNIEnv *, jobject, jint, jdouble, jdouble, jdouble);

/*
 * Class:     fiat_rdatsrv_weibull_NativeWeibull
 * Method:    generateSamples
 * Signature: (IIIIIJZ)I
 */
JNIEXPORT jint JNICALL Java_fiat_rdatsrv_weibull_NativeWeibull_generateSamples
  (JNIEnv *, jobject, jint, jint, jint, jint, jint, jlong, jboolean);

/*
 * Class:     fiat_rdatsrv_weibull_NativeWeibull
 * Method:    getStatus
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_fiat_rdatsrv_weibull_NativeWeibull_getStatus
  (JNIEnv *, jobject, jint);

/*
 * Class:     fiat_rdatsrv_weibull_NativeWeibull
 * Method:    getProgress
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_fiat_rdatsrv_weibull_NativeWeibull_getProgress
  (JNIEnv *, jobject, jint);

/*
 * Class:     fiat_rdatsrv_weibull_NativeWeibull
 * Method:    estimateJointParameterDensity
 * Signature: (IZI)I
 */
JNIEXPORT jint JNICALL Java_fiat_rdatsrv_weibull_NativeWeibull_estimateJointParameterDensity
  (JNIEnv *, jobject, jint, jboolean, jint);

/*
 * Class:     fiat_rdatsrv_weibull_NativeWeibull
 * Method:    getJointDensities
 * Signature: (II[D[D[D)I
 */
JNIEXPORT jint JNICALL Java_fiat_rdatsrv_weibull_NativeWeibull_getJointDensities
  (JNIEnv *, jobject, jint, jint, jdoubleArray, jdoubleArray, jdoubleArray);

/*
 * Class:     fiat_rdatsrv_weibull_NativeWeibull
 * Method:    computeParameter
 * Signature: (II[D[D[D[D[D[D[D[D)I
 */
JNIEXPORT jint JNICALL Java_fiat_rdatsrv_weibull_NativeWeibull_computeParameter
  (JNIEnv *, jobject, jint, jint, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray);

/*
 * Class:     fiat_rdatsrv_weibull_NativeWeibull
 * Method:    computeMeasures
 * Signature: (II[D[D[D[D[D[D[D[D[D)I
 */
JNIEXPORT jint JNICALL Java_fiat_rdatsrv_weibull_NativeWeibull_computeMeasures
  (JNIEnv *, jobject, jint, jint, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray);

/*
 * Class:     fiat_rdatsrv_weibull_NativeWeibull
 * Method:    computeWeibullMTTF
 * Signature: (IDD)D
 */
JNIEXPORT jdouble JNICALL Java_fiat_rdatsrv_weibull_NativeWeibull_computeWeibullMTTF
  (JNIEnv *, jobject, jint, jdouble, jdouble);

#ifdef __cplusplus
}
#endif
#endif
