/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class fiat_rdatsrv_ccf_NativeCCF */

#ifndef _Included_fiat_rdatsrv_ccf_NativeCCF
#define _Included_fiat_rdatsrv_ccf_NativeCCF
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     fiat_rdatsrv_ccf_NativeCCF
 * Method:    createCCFSession
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_fiat_rdatsrv_ccf_NativeCCF_createCCFSession
  (JNIEnv *, jobject);

/*
 * Class:     fiat_rdatsrv_ccf_NativeCCF
 * Method:    destroyCCFSession
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_fiat_rdatsrv_ccf_NativeCCF_destroyCCFSession
  (JNIEnv *, jobject, jint);

/*
 * Class:     fiat_rdatsrv_ccf_NativeCCF
 * Method:    initialize
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_fiat_rdatsrv_ccf_NativeCCF_initialize
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     fiat_rdatsrv_ccf_NativeCCF
 * Method:    setPrior
 * Signature: (II[D[D)I
 */
JNIEXPORT jint JNICALL Java_fiat_rdatsrv_ccf_NativeCCF_setPrior
  (JNIEnv *, jobject, jint, jint, jdoubleArray, jdoubleArray);

/*
 * Class:     fiat_rdatsrv_ccf_NativeCCF
 * Method:    setLikelihood
 * Signature: (I[I)I
 */
JNIEXPORT jint JNICALL Java_fiat_rdatsrv_ccf_NativeCCF_setLikelihood
  (JNIEnv *, jobject, jint, jintArray);

/*
 * Class:     fiat_rdatsrv_ccf_NativeCCF
 * Method:    runAnalysis
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_fiat_rdatsrv_ccf_NativeCCF_runAnalysis
  (JNIEnv *, jobject, jint);

/*
 * Class:     fiat_rdatsrv_ccf_NativeCCF
 * Method:    getPosteriorDistHandle
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_fiat_rdatsrv_ccf_NativeCCF_getPosteriorDistHandle
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
