/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class fiat_rdatsrv_distribution_NativeDistribution */

#ifndef _Included_fiat_rdatsrv_distribution_NativeDistribution
#define _Included_fiat_rdatsrv_distribution_NativeDistribution
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     fiat_rdatsrv_distribution_NativeDistribution
 * Method:    create
 * Signature: (IIDD)I
 */
JNIEXPORT jint JNICALL Java_fiat_rdatsrv_distribution_NativeDistribution_create
  (JNIEnv *, jobject, jint, jint, jdouble, jdouble);

/*
 * Class:     fiat_rdatsrv_distribution_NativeDistribution
 * Method:    destroy
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_fiat_rdatsrv_distribution_NativeDistribution_destroy
  (JNIEnv *, jobject, jint);

/*
 * Class:     fiat_rdatsrv_distribution_NativeDistribution
 * Method:    getX
 * Signature: (ID)D
 */
JNIEXPORT jdouble JNICALL Java_fiat_rdatsrv_distribution_NativeDistribution_getX
  (JNIEnv *, jobject, jint, jdouble);

/*
 * Class:     fiat_rdatsrv_distribution_NativeDistribution
 * Method:    getPDF
 * Signature: (ID)D
 */
JNIEXPORT jdouble JNICALL Java_fiat_rdatsrv_distribution_NativeDistribution_getPDF
  (JNIEnv *, jobject, jint, jdouble);

/*
 * Class:     fiat_rdatsrv_distribution_NativeDistribution
 * Method:    getCDF
 * Signature: (ID)D
 */
JNIEXPORT jdouble JNICALL Java_fiat_rdatsrv_distribution_NativeDistribution_getCDF
  (JNIEnv *, jobject, jint, jdouble);

/*
 * Class:     fiat_rdatsrv_distribution_NativeDistribution
 * Method:    getQuantile
 * Signature: (ID)D
 */
JNIEXPORT jdouble JNICALL Java_fiat_rdatsrv_distribution_NativeDistribution_getQuantile
  (JNIEnv *, jobject, jint, jdouble);

/*
 * Class:     fiat_rdatsrv_distribution_NativeDistribution
 * Method:    getMean
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_fiat_rdatsrv_distribution_NativeDistribution_getMean
  (JNIEnv *, jobject, jint);

/*
 * Class:     fiat_rdatsrv_distribution_NativeDistribution
 * Method:    getMedian
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_fiat_rdatsrv_distribution_NativeDistribution_getMedian
  (JNIEnv *, jobject, jint);

/*
 * Class:     fiat_rdatsrv_distribution_NativeDistribution
 * Method:    getVariance
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_fiat_rdatsrv_distribution_NativeDistribution_getVariance
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
