#ifndef RDATDEF_H_
#define RDATDEF_H_

// Definitions for Distribution Type
#undef REDCASSRV_BETA_DIST
#define REDCASSRV_BETA_DIST 401L

#undef REDCASSRV_BINOMIAL_DIST
#define REDCASSRV_BINOMIAL_DIST 402L

#undef REDCASSRV_GAMMA_DIST
#define REDCASSRV_GAMMA_DIST 403L

#undef REDCASSRV_NORMAL_DIST
#define REDCASSRV_NORMAL_DIST 404L

#undef REDCASSRV_LOGNORMAL_DIST
#define REDCASSRV_LOGNORMAL_DIST 405L

#undef REDCASSRV_TLOGNORMAL_DIST
#define REDCASSRV_TLOGNORMAL_DIST 406L

#undef REDCASSRV_UNIFORM_DIST
#define REDCASSRV_UNIFORM_DIST 407L

#undef REDCASSRV_LOGUNIFORM_DIST
#define REDCASSRV_LOGUNIFORM_DIST 408L

#undef REDCASSRV_POSISSON_DIST
#define REDCASSRV_POSISSON_DIST 409L

#undef REDCASSRV_TABULAR_DIST
#define REDCASSRV_TABULAR_DIST 410L

#undef REDCASSRV_CHISQUARE_DIST
#define REDCASSRV_CHISQUARE_DIST 411L

#undef REDCASSRV_EXPONENTIAL_DIST
#define REDCASSRV_EXPONENTIAL_DIST 412L

#undef REDCASSRV_INVERTEDGAMMA_DIST
#define REDCASSRV_INVERTEDGAMMA_DIST 413L

#undef REDCASSRV_INVCHISQUARE_DIST
#define REDCASSRV_INVCHISQUARE_DIST 414L

#undef REDCASSRV_STUDENTT_DIST
#define REDCASSRV_STUDENTT_DIST 415L

#undef REDCASSRV_WEIBULL_DIST
#define REDCASSRV_WEIBULL_DIST 416L

// Definitions for Distribution input modes
#undef REDCASSRV_ALPHABETA_MODE
#define REDCASSRV_ALPHABETA_MODE 500L

#undef REDCASSRV_MEANSD_MODE
#define REDCASSRV_MEANSD_MODE 501L

#undef REDCASSRV_5TH95TH_MODE
#define REDCASSRV_5TH95TH_MODE 502L

#undef REDCASSRV_ALPHATHETA_MODE
#define REDCASSRV_ALPHATHETA_MODE 503L

#undef REDCASSRV_MEDIANTAU_MODE
#define REDCASSRV_MEDIANTAU_MODE 504L

#undef REDCASSRV_MEDIANEF_MODE
#define REDCASSRV_MEDIANEF_MODE 505L

#undef REDCASSRV_MEANEF_MODE
#define REDCASSRV_MEANEF_MODE 506L

#undef REDCASSRV_NUTAU_MODE
#define REDCASSRV_NUTAU_MODE 507L

#undef REDCASSRV_MINMAX_MODE
#define REDCASSRV_MINMAX_MODE 508L

#undef REDCASSRV_EVENTTIME_MODE
#define REDCASSRV_EVENTTIME_MODE 509L

#undef REDCASSRV_EVENTDEMANDS_MODE
#define REDCASSRV_EVENTDEMANDS_MODE 510L

#undef REDCASSRV_DEGREEOFFREEDOM
#define REDCASSRV_DEGREEOFFREEDOM 511L

#undef REDCASSRV_LAMBDA
#define REDCASSRV_LABMDA 512L

#undef REDCASSRV_SHAPESCALE
#define REDCASSRV_SHAPESCALE 513L

#endif